spring:
  application:
    name: omp-wechat-webin
  profiles:
    active: dev
  jmx:
    enabled: true

# 应用服务 WEB 访问端口
server:
  port: 8081
  servlet:
    context-path: /omp-wechat-webin/

app:
  version: @project.version@
  build:
    time: @timestamp@
  openlog: y




